export enum TypeEnum {
    "Acier" = 0,
    "Combat" = 1,
    "Dragon" = 2,
    "Eau" = 3,
    "Electrik" = 4,
    "Fée" = 5,
    "Feu" = 6,
    "Glace" = 7,
    "Insecte" = 8,
    "Normal" = 9,
    "Plante" = 10,
    "Poison" = 11,
    "Psy" = 12,
    "Roche" = 13,
    "Sol" = 14,
    "Spectre" = 15,
    "Ténèbres" = 16,
    "Vol" = 17
}